name: csc490
channels:
  - iopath
  - fvcore
  - pytorch
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pytorch=1.10.0
  - pytorch3d=0.6.1
  - torchvision=0.11.1
  - fire=0.4.0
  - fvcore=0.1.5
  - iopath=0.1.9
  - matplotlib=3.5.0
  - tqdm=4.62.3
  - pandas=1.3.5
  - pytest=6.2.5
